name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and publish
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./CarvedRock.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/carvedrockapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/carvedrockapi:${{ github.run_number }}
        
